import { builtinModules, createRequire } from "node:module";

interface PackageJson {
	dependencies?: Record<string, string>;
	peerDependencies?: Record<string, string>;
}

const builtins = new Set([...builtinModules, ...builtinModules.map((name) => `node:${name}`)]);

export const generatedBanner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

export function isNodeBuiltin(id: string): boolean {
	return builtins.has(id);
}

export function matchesPackage(id: string, packageName: string): boolean {
	return id === packageName || id.startsWith(`${packageName}/`);
}

export function externalize(packageNames: string[]) {
	return (id: string): boolean =>
		isNodeBuiltin(id) || packageNames.some((packageName) => matchesPackage(id, packageName));
}

export function packageDependencyExternals(importMetaUrl: string) {
	const require = createRequire(importMetaUrl);
	const packageJson = require("./package.json") as PackageJson;
	const packageNames = Object.keys({
		...packageJson.dependencies,
		...packageJson.peerDependencies,
	});

	return externalize(packageNames);
}
