import * as ConfluencePageConfig from "./ConniePageConfig";
import * as ConfluenceUploadSettings from "./Settings";
import {
	AlwaysADFProcessingPlugins,
	createPublisherFunctions,
	executeADFProcessingPipeline,
	executeADFProcessingPipelineEffect,
	getMermaidFileName,
	MermaidRendererPlugin,
	type ADFProcessingPlugin,
	type ChartData,
	type MermaidRenderer,
	type PublisherFunctions,
} from "./ADFProcessingPlugins";
import { renderADFDoc } from "./ADFToMarkdown";
import { type RequiredConfluenceClient } from "./ConfluenceClient";
import {
	MarkdownConfluencePlatformLive,
	MarkdownConfluenceRuntime,
	RuntimeEnvironmentLive,
	RuntimeEnvironmentService,
	runEffect,
	type MarkdownConfluencePlatform,
	type RuntimeEnvironment,
} from "./effects";
import {
	MarkdownWorkspaceLive,
	MarkdownWorkspaceService,
	loadMarkdownWorkspace,
	makeMarkdownWorkspaceEffect,
	type BinaryFile,
	type FilesToUpload,
	type MarkdownFile,
	type MarkdownWorkspace,
} from "./MarkdownWorkspace";
import { convertMDtoADF, parseMarkdownToADF, stripMarkdownHtmlComments } from "./MdToADF";
import {
	Publisher,
	type ConfluenceAdfFile,
	type ConfluenceNode,
	type ConfluenceTreeNode,
	type LocalAdfFile,
	type LocalAdfFileTreeNode,
	type UploadAdfFileResult,
} from "./Publisher";
import {
	ConfluenceSettingsLive,
	confluenceSettingsConfig,
	loadConfluenceSettings,
	loadConfluenceSettingsEffect,
	makeConfluenceSettingsConfigProvider,
	parseConfluenceSettingsEffect,
} from "./SettingsConfig";

export {
	AlwaysADFProcessingPlugins,
	ConfluencePageConfig,
	ConfluenceSettingsLive,
	ConfluenceUploadSettings,
	MarkdownConfluencePlatformLive,
	MarkdownConfluenceRuntime,
	MarkdownWorkspaceLive,
	MarkdownWorkspaceService,
	MermaidRendererPlugin,
	Publisher,
	RuntimeEnvironmentLive,
	RuntimeEnvironmentService,
	confluenceSettingsConfig,
	convertMDtoADF,
	createPublisherFunctions,
	executeADFProcessingPipeline,
	executeADFProcessingPipelineEffect,
	getMermaidFileName,
	loadConfluenceSettings,
	loadConfluenceSettingsEffect,
	loadMarkdownWorkspace,
	makeConfluenceSettingsConfigProvider,
	makeMarkdownWorkspaceEffect,
	parseConfluenceSettingsEffect,
	parseMarkdownToADF,
	renderADFDoc,
	runEffect,
	stripMarkdownHtmlComments,
	type ADFProcessingPlugin,
	type BinaryFile,
	type ChartData,
	type ConfluenceAdfFile,
	type ConfluenceNode,
	type ConfluenceTreeNode,
	type FilesToUpload,
	type LocalAdfFile,
	type LocalAdfFileTreeNode,
	type MarkdownConfluencePlatform,
	type MarkdownFile,
	type MarkdownWorkspace,
	type MermaidRenderer,
	type PublisherFunctions,
	type RequiredConfluenceClient,
	type RuntimeEnvironment,
	type UploadAdfFileResult,
};
