import builtins from "builtin-modules";
import esbuild from "esbuild";
import { copy } from "esbuild-plugin-copy";
import { copyFileSync, watch, writeFileSync } from "fs";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outDir = prod
	? "dist"
	: "../../dev-vault/.obsidian/plugins/obsidian-confluence";

const buildConfig = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "chrome106",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: outDir,
	mainFields: ["module", "main"],
	minify: true,
	metafile: true,
	plugins: [
		copy({
			resolveFrom: "cwd",
			assets: {
				from: [
					"packages/obsidian/styles.css",
					"packages/obsidian/manifest.json",
				],
				to: [
					prod
						? "packages/obsidian/dist"
						: "dev-vault/.obsidian/plugins/obsidian-confluence",
				],
			},
		}),
	],
};

if (prod) {
	const buildResult = await esbuild.build(buildConfig);
	writeFileSync("./dist/meta.json", JSON.stringify(buildResult.metafile));
	// Copy styles.css to dist folder in production mode
	copyFileSync("styles.css", "./dist/styles.css");
} else {
	const context = await esbuild.context(buildConfig);
	await context.watch();
	// Copy styles.css to dev environment
	copyFileSync(
		"styles.css",
		"../../dev-vault/.obsidian/plugins/obsidian-confluence/styles.css",
	);

	// Watch for changes to styles.css
	console.log("Watching for changes to styles.css...");
	watch("styles.css", (eventType, filename) => {
		if (eventType === "change") {
			console.log("styles.css changed, updating...");
			copyFileSync(
				"styles.css",
				"../../dev-vault/.obsidian/plugins/obsidian-confluence/styles.css",
			);
			console.log("styles.css updated in dev environment");
		}
	});
}
