import esbuild from "esbuild";
import process from "process";
import { writeFileSync } from 'fs';
import builtins from 'builtin-modules'
import { copy } from 'esbuild-plugin-copy';



const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const buildConfig = {
	banner: {
		js: banner,
	},
	entryPoints: ['src/index.ts'],
	bundle: true,
	format: 'cjs',
	target: 'node16',
	platform: 'node',
	logLevel: "info",
	sourcemap: true,
	treeShaking: true,
	outdir: 'dist',
	mainFields: ['module', 'main'],
	minify: true,
	metafile: true,
	external: [
		...builtins
	],
	plugins: [
		copy({
		  // this is equal to process.cwd(), which means we use cwd path as base path to resolve `to` path
		  // if not specified, this plugin uses ESBuild.build outdir/outfile options as base path.
		  resolveFrom: 'cwd',
		  assets: {
			from: ['../mermaid-puppeteer-renderer/dist/mermaid_renderer.html'],
			to: ['./dist/mermaid_renderer.html'],
		  },
		  watch: true,
		}),
	  ],
};

if (prod) {
	const buildResult = await esbuild.build(buildConfig);
	writeFileSync("./dist/meta.json", JSON.stringify(buildResult.metafile));
} else {
	const context = await esbuild.context(buildConfig);
	await context.watch();	
}